config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:new, :create, :show, :index]
  devise_for :users, :controllers => {
    registrations: 'registrations'
  }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 3 }
  validates :body, presence: true, length: { in: 10...5000 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
  
  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
    def sign_up_params
      params.require(:user).permit(:email, :password, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<h1>Welcome</h1>
<% if user_signed_in? %>
  <div>Welcome, <%= current_user.username %>!</div>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <div>
    <%= link_to "Sign in", new_user_session_path %> |
    <%= link_to "Sign up", new_user_registration_path %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Members</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model:post) do |form| %>
  <% if post.errors.any? %>
      <h3><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h3>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  <%= form.label :title %>
  <%= form.text_field :title %>
  </div>

  <div>
  <%= form.label :body %>
  <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div>
  <p>
    <h2><%= post.title %></h2>
  </p>

  <p>
    <%= post.body %>
  </p>

  <% if user_signed_in? %>
  <p>
    Posted by:
    <%= post.user.username %>
  </p>
  <% end %>

  </div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% @posts.each do |post| %>
  <%= render post %>
  <%= link_to "Show this post", post %>
<% end %>
<hr>
<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

<br>

<%= link_to "Back to posts", posts_path %>

app/views/posts/show.html.erb
<%= render @post %>

<%= link_to "Back to posts", posts_path %>